export const NCAA_LOGO_MAP: Record<string, string> = {
    // Spaceless keys (from utils/mapping.py normalization)
    "louisianamonroe": "la-monroe",
    "ulmonroe": "la-monroe",
    "ulm": "la-monroe",
    "northernkentucky": "northern-ky",
    "detroitmercy": "detroit",
    "mountstmarys": "mt-st-marys",
    "stmarysca": "st-marys-ca",
    "pennsylvania": "penn", // Try penn if pennsylvania fails, but verify.
    "penn": "penn",
    "thecitadel": "citadel",
    "uncwilmington": "unc-wilmington",
    "uncgreensboro": "unc-greensboro",
    "uncasheville": "unc-asheville",
    "centralconnecticut": "central-conn-st",
    "fairleighdickinson": "fairleigh-dickinson",
    "stbonaventure": "st-bonaventure",
    "miamioh": "miami-oh",
    "miamifl": "miami-fl",
    "olemiss": "mississippi",
    "mississippi": "mississippi",
    "ncstate": "nc-state",

    // Original Spaced Keys (Keep for safety)
    "georgia southern": "ga-southern",
    "georgiasouthern": "ga-southern",
    "louisiana monroe": "la-monroe",
    "mount st. mary's": "mt-st-marys",
    "detroit mercy": "detroit",
    "northern kentucky": "northern-ky",
    "unc wilmington": "unc-wilmington",
    "unc greensboro": "unc-greensboro",
    "unc asheville": "unc-asheville",
    "central connecticut": "central-conn-st",
    "central connecticut state": "central-conn-st",
    "fdu": "fairleigh-dickinson",
    "fairleigh dickinson": "fairleigh-dickinson",
    "st. bonaventure": "st-bonaventure",
    "saint mary's": "st-marys-ca",
    "st. mary's (ca)": "st-marys-ca",
    "miami (oh)": "miami-oh",
    "miami (fl)": "miami-fl",
    "ole miss": "mississippi",
    "uconn": "uconn",
    "umass": "massachusetts",
    "smu": "smu",
    "tcu": "tcu",
    "utep": "utep",
    "utsa": "utsa",
    "vcu": "vcu",
    "uab": "uab",
    "ucf": "ucf",
    "unlv": "unlv",
    "usc": "usc",
    "lsu": "lsu",
    "byu": "byu"
};
